### ISSUE TITLE
Automatic configuration of prometheus remote_read broken

### ISSUE THREAD

**Issue by jpigree** [timescale/timescale-observability#28]
Hi. I updated yesterday to the` 0.1.0-alpha.3` release but since then, the prometheus instance spawned with the chart fails to read from the database.

I tracked down the error into a [commit](https://github.com/timescale/timescale-prometheus/commit/edd1162917f081b4c016416e89102a1b1a113bb1#diff-6c0ecadafff2d91469d3112783460222) in the timescale-prometheus repository. This commit changes the name of the timescale-prometheus connector's service name.

However, this change wasn't taken into account in the [autogenerated prometheus configuration](https://github.com/timescale/timescale-observability/blob/master/chart/templates/prometheus-conf.yaml#L23):

We have two ways to fix this:
- revert the service name commit
- (quick fix) update the name of the service in the remote_read and remote_write urls in the prometheus configuration template (this is what I did to fix the issue)
- (long fix) update the prometheus configuration and find a way to keep it in sync between the two charts (a variable should do). This will require to update both charts. Don't know if this is worth the effort though.

I tried to workaround the bug by [specifying the remote_read myself](https://github.com/timescale/timescale-observability/blob/master/chart/templates/prometheus-conf.yaml#L44) using the `.Values.prometheus.server.remoteRead` key but wasn't able to make it work.

I have an indentation issue:
```
helm upgrade --install --dry-run --debug metrics timescale/timescale-observability --version=0.1.0-alpha.3 -f helm/metrics.yaml | grep "remote_read" -A 5
    remote_read:
      - url: http://metrics-timescale-prometheus.monitoring.svc.cluster.local:9201/read
    - url: http://metrics-timescale-prometheus-connector.monitoring.svc.cluster.local:9201/read
```
I managed to fix the chart by changing this line:
`{{ $root.Values.prometheus.server.remoteRead | toYaml | indent 4 }}`
into:
`{{ $root.Values.prometheus.server.remoteRead | toYaml | indent 6 }}`

I can fix both those issues and submit a PR if this helps.
